# Generated by Django 5.0.6 on 2024-06-15 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_borrowedbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='books',
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='books',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
