# Generated by Django 5.0.6 on 2024-06-15 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_borrowedbook_books_borrowedbook_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedbook',
            old_name='books',
            new_name='book',
        ),
    ]
