# Generated by Django 5.0.6 on 2024-06-15 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_books_borrowedbook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 15, 6, 32, 1, 557840, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
